---
title: {{ title }}
output:
  pagedown::html_resume:
    css: ["default-fonts", "default-page", "default", "css/extra.css", "css/fonts.css"]
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE
)
library(icons)
library(kableExtra)
library(yaml)
library(htmltools)
rfa <- function(...) fontawesome(...)
options(htmltools.dir.version = FALSE, htmltools.preserve.raw = FALSE)
```




<div class="details_container">

<div class="left details font90 width60">

<div class="main_title">
  <h1> Kevin Cazelles </h1>
  <h3> `r rfa("chevron-right")` Data and computational scientist</h3>
</div>

For the past 10 years, I have conducted theoretical, statistical and computational research in ecology. I have significantly contributed to the scientific literature and presented my findings in various international conferences. In most projects I have been involved in, I have designed, developed and contributed to software that implement mathematical and statistical modelling as well as reproducible analysis pipelines. Today, I am seeking job opportunities to leverage my expertise in mathematics, statistics, data science and computational science. 

</div>


<div class="right details font85 width40  ">

```{R perso_details, echo = FALSE, results = "asis"}
insert_perso_details()
```  
</div>


</div>



<div class="left sections_container width100">



## `r rfa("graduation-cap")` Education

<hr>

```{R edu, echo = FALSE, results = "asis"}
insert_education()
```


## `r rfa("briefcase")` Professional experience 

<hr>


```{R xp, echo = FALSE, results = "asis"}
insert_xp(use_did = TRUE)
```

## `r rfa("tachometer-alt")` Computational Skills

<hr>


<div class="left details width100">


<div class="left width50">

#### Scientific programming

```{R sci_pro, echo = FALSE, results = "asis"}
insert_skills()
```

#### Reproducibility

```{R repro, echo = FALSE, results = "asis"}
insert_skills(what = "repro")
```

</div>


<div class="right width50">

#### Database

```{R db, echo = FALSE, results = "asis"}
insert_skills(what = "db")
```


#### Modern web technologies

```{R web, echo = FALSE, results = "asis"}
insert_skills(what = "web")
```

#### Document preparation

```{R doc, echo = FALSE, results = "asis"}
insert_skills(what = "db")
```

</div>


</div>



## `r rfa('university')` Teaching

<hr>

```{R teach, echo = FALSE, results = "asis"}
insert_teach()
```

## `r rfa('user-graduate')` Mentoring experience

<hr>

```{R mentor, echo = FALSE, results = "asis"}
insert_mentor()
```



## `r rfa("book")` Publications

<hr>

### Peer reviewed

```{R pubs, echo = FALSE, results = "asis"}
insert_pubs()
```

### Popularization

```{R popu, echo = FALSE, results = "asis"}
insert_popu()
```


### Editorial and review activities

```{R reviewer, echo = FALSE, results = "asis"}
insert_reviewer()
```



## `r rfa("code")` Software

<hr>

This section includes a subset of my contributions to open-source software. If you are interested in seeing more, most of my contributions can be found on my [GitHub account](https://github.com/KevCaz), see also the section "[notes](https://kevcaz.github.io/notes/)" of my website. 

<br>


### `r rfa("r-project")` packages

<div class="font90">

Below is a selection of R packages I significantly contributed to. 

</div>

```{R rpkgs, echo = FALSE, results = "asis"}
insert_soft()
```


### Research compendia 

<div class="font90">

I am strongly committed to making the research I do reproducible. To that end, every study I lead comes with a [research compendium](https://research-compendium.science/). Below is a list of selected research compendia that were published along side with the corresponding paper. 

</div>

```{R compendia, echo = FALSE, results = "asis"}
insert_compendia()
```


### Manuals  

```{R man, echo = FALSE, results = "asis"}
insert_man()
```




## `r rfa("bullhorn")` Presentations

<hr>


### Talks 

```{R talks, echo = FALSE, results = "asis"}
insert_talks()
```

### Seminars

```{R seminars, echo = FALSE, results = "asis"}
insert_sems()
```

### Posters

```{R posters, echo = FALSE, results = "asis"}
insert_posters()
```



## `r rfa("search-dollar")` Grants and awards

<hr>

```{R grants, echo = FALSE, results = "asis"}
insert_grants()
```



## `r rfa("newspaper")` Media Coverage

<hr>

```{R media, echo = FALSE, results = "asis"}
insert_media()
```



</div>