---
title: {{ title }}
output:
  pagedown::html_resume:
    css: ["default-fonts", "default-page", "default", "css/extra.css", "css/fonts.css"]
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE
)
library(icons)
library(kableExtra)
library(yaml)
library(htmltools)
rfa <- function(...) fontawesome(...)
options(htmltools.dir.version = FALSE, htmltools.preserve.raw = FALSE)
```




<div class = "details_container">

<div class="left details font90 width60">

<div class = "main_title">
  <h1> Kevin Cazelles </h1>
  <h3> `r rfa("chevron-right")` Theoretical and computational ecologist</h3>
</div>

Je suis un écologue qui utilise l'analyse, les probabilités les statistiques, la science des données et la science numérique pour étudier les réseaux écologiques et comment le changement global les affectent, dans le but de conservé le bon fonctionnement des écosystèmes et la biodiversité qui sont sont essentielles pour notre santé et notre bien-être.

</div>


<div class="right details font85 width40">

```{R perso_details, echo = FALSE, results = "asis"}
insert_perso_details()
```  
</div>


</div>



<div class="left sections_container width100">



## `r rfa("graduation-cap")` Formation

<hr>

```{R edu, echo = FALSE, results = "asis"}
insert_education("data/fr/education.yaml")
```


## `r rfa("briefcase")` Expérience professionnelle

<hr>


```{R xp, echo = FALSE, results = "asis"}
insert_xp("data/fr/prof_xp.yaml")
```

## `r rfa("tachometer-alt")` Compétences computationnelles

<hr>


<div class="left details width100">


<div class="left width50">

#### Calcul scientifique

```{R sci_pro, echo = FALSE, results = "asis"}
insert_skills()
```

#### Reproductibilité

```{R repro, echo = FALSE, results = "asis"}
insert_skills(what = "repro")
```

</div>


<div class="right width50">

#### Bases de données

```{R db, echo = FALSE, results = "asis"}
insert_skills(what = "db")
```


#### Technologies Internet modernes

```{R web, echo = FALSE, results = "asis"}
insert_skills(what = "web")
```

#### Préparation de documents

```{R doc, echo = FALSE, results = "asis"}
insert_skills(what = "db")
```

</div>


</div>



## `r rfa('university')` Enseignement

<hr>

```{R teach, echo = FALSE, results = "asis"}
insert_teach()
```

## `r rfa('user-graduate')` Expérience de mentorat

<hr>

```{R mentor, echo = FALSE, results = "asis"}
insert_mentor()
```



## `r rfa("book")` Publications

<hr>

### Revues internationales à commité de lecture

```{R pubs, echo = FALSE, results = "asis"}
insert_pubs()
```

### Vulgarisation scientifique

```{R popu, echo = FALSE, results = "asis"}
insert_popu()
```


### Activité de réviseur

```{R reviewer, echo = FALSE, results = "asis"}
insert_reviewer()
```



## `r rfa("code")` Logiciels

<hr>

This section includes a subset of my contributions to open-source software. If you are interested in seeing more, most of my contributions can be found on my [GitHub account](https://github.com/KevCaz), see also the section "[notes](https://kevcaz.github.io/notes/)" of my website. 



### `r rfa("r-project")` packages

<div class="font90">

Below is a selection of R packages I significantly contributed to. 

</div>

```{R rpkgs, echo = FALSE, results = "asis"}
insert_soft()
```


### Compendia de recherche

<div class="font90">

I am strongly committed to making the science I do reproducible. To that end, every study I lead comes with a [research compendium](https://research-compendium.science/). Below is a list of selected research compendia that were published along side with the corresponding paper. 

</div>

```{R compendia, echo = FALSE, results = "asis"}
insert_compendia()
```


### Manuels  

```{R man, echo = FALSE, results = "asis"}
insert_man()
```




## `r rfa("bullhorn")` Présentations

<hr>


### Présentations orales

```{R talks, echo = FALSE, results = "asis"}
insert_talks()
```

### Séminaires

```{R seminars, echo = FALSE, results = "asis"}
insert_sems()
```

### Posters

```{R posters, echo = FALSE, results = "asis"}
insert_posters()
```



## `r rfa("search-dollar")` Bourses et récompenses

<hr>

```{R grants, echo = FALSE, results = "asis"}
insert_grants()
```



## `r rfa("newspaper")` Couverture médiatique

<hr>

```{R media, echo = FALSE, results = "asis"}
insert_media()
```


</div>